### ISSUE TITLE
Adding HTML wrappers to allow a full responsive design

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zmarkdown#166]
If we want to make a full responsive design, we need some wrappers around :

- [ ] tables
- [ ] grid tables
- [ ] video iframes
- [ ] jsfiddle iframes

## tables and grid tables

we need this HTML :

```html
<div class="table-wrapper"><table>...</table></div>
```

to be able to use this CSS :

```css
.table-wrapper {
    overflow-x: auto;
}
```

## video iframes

we need to replace this :

```html
<p><iframe width="-- px" height="-- px"></iframe></p>
```

by this

```html
<div class="video-container" style="max-width: -- px; max-height: -- px;"><!-- the same width and heigh that were on the iframe element -->
  <div class="video-wrapper" style="padding-bottom: -- %;"><!-- the value is the ratio : height * 100 / width -->
    <iframe ...></iframe>
  </div>
</div>
```

to be able to use this CSS :

```css
.video-container {
    margin: 0 auto;
}
.video-wrapper {
    position: relative;
}
.video-wrapper iframe {
    position:absolute;
    width: 100%;
    height: 100%;
}
```

## jsfiddle iframes

we just need a wrapper (either a `<div>` or a `<p>`) with the class `jsfiddle-wrapper` and this CSS (the same as for the tables :

```css
.iframe-wrapper {
    overflow-x: auto;
}
```
