### ISSUE TITLE
[rebber] Error with code and highlights

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#262]
The parsing of 

    ```css hl_lines="2"
    .tmp {
      font-weighth: bold;
    }
    ```

[Currently](https://zestedesavoir.github.io/zmarkdown/public/latex.html) gives 

```latex
\begin{CodeBlock}[]["2"]{css}
.tmp {
  font-weighth: bold;
}
\end{CodeBlock}
```

But should give 
```latex
\begin{CodeBlock}[][2]{css}
.tmp {
  font-weighth: bold;
}
\end{CodeBlock}
```

The quotes disturbs minted ^^
